run:
  deadline: 1m
  tests: false
  skip-files:
    - ".*\\.pb\\.go"
    - ".*\\.gen\\.go"

linters-settings:
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US
  gci:
    sections:
      - Std
      - Def
      - prefix(github.com/lovoo/protoc-gen-go-grpcmock)

severity:
  default-severity: warning

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - gomodguard
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
