// Code generated by protoc-gen-go-grpcmock. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpcmock v0.5.0
// - protoc                 v3.21.1
// - testify                v1.7.1
// source: route_guide.proto

package routeguide

import (
	context "context"
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

func AnyPoint() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*routeguide.Point")
}

func AnyRectangle() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*routeguide.Rectangle")
}

func AnyFeature() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*routeguide.Feature")
}

func AnyRouteNote() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*routeguide.RouteNote")
}

func AnyRouteSummary() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*routeguide.RouteSummary")
}

func AnyRouteGuide_ListFeaturesClient() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*routeguide.RouteGuide_ListFeaturesClient")
}

func AnyRouteGuide_ListFeaturesServer() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*routeguide.RouteGuide_ListFeaturesServer")
}

func AnyRouteGuide_RecordRouteClient() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*routeguide.RouteGuide_RecordRouteClient")
}

func AnyRouteGuide_RecordRouteServer() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*routeguide.RouteGuide_RecordRouteServer")
}

func AnyRouteGuide_RouteChatClient() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*routeguide.RouteGuide_RouteChatClient")
}

func AnyRouteGuide_RouteChatServer() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*routeguide.RouteGuide_RouteChatServer")
}

type mockRouteGuideClient struct {
	mock.Mock
}

func NewMockRouteGuideClient() *mockRouteGuideClient {
	return &mockRouteGuideClient{}
}

func (c *mockRouteGuideClient) GetFeature(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Feature, error) {
	opts0 := []interface{}{ctx, in}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(*Feature), args.Error(1)
}

func (c *mockRouteGuideClient) OnGetFeature(ctx interface{}, in interface{}, opts ...interface{}) *mock.Call {
	return c.On("GetFeature", append([]interface{}{ctx, in}, opts...)...)
}

func (c *mockRouteGuideClient) ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc.CallOption) (RouteGuide_ListFeaturesClient, error) {
	opts0 := []interface{}{ctx, in}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(RouteGuide_ListFeaturesClient), args.Error(1)
}

func (c *mockRouteGuideClient) OnListFeatures(ctx interface{}, in interface{}, opts ...interface{}) *mock.Call {
	return c.On("ListFeatures", append([]interface{}{ctx, in}, opts...)...)
}

type mockRouteGuide_ListFeaturesClient struct {
	mock.Mock
}

func NewMockRouteGuide_ListFeaturesClient() *mockRouteGuide_ListFeaturesClient {
	return &mockRouteGuide_ListFeaturesClient{}
}

func (x *mockRouteGuide_ListFeaturesClient) Header() (metadata.MD, error) {
	args := x.Called()
	return args.Get(0).(metadata.MD), args.Error(1)
}

func (x *mockRouteGuide_ListFeaturesClient) Trailer() metadata.MD {
	args := x.Called()
	return args.Get(0).(metadata.MD)
}

func (x *mockRouteGuide_ListFeaturesClient) CloseSend() error {
	args := x.Called()
	return args.Error(0)
}

func (x *mockRouteGuide_ListFeaturesClient) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *mockRouteGuide_ListFeaturesClient) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *mockRouteGuide_ListFeaturesClient) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *mockRouteGuide_ListFeaturesClient) Recv() (*Feature, error) {
	args := x.Called()
	return args.Get(0).(*Feature), args.Error(1)
}

func (x *mockRouteGuide_ListFeaturesClient) OnRecv() *mock.Call {
	return x.On("Recv")
}

func (c *mockRouteGuideClient) RecordRoute(ctx context.Context, opts ...grpc.CallOption) (RouteGuide_RecordRouteClient, error) {
	opts0 := []interface{}{ctx}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(RouteGuide_RecordRouteClient), args.Error(1)
}

func (c *mockRouteGuideClient) OnRecordRoute(ctx interface{}, opts ...interface{}) *mock.Call {
	return c.On("RecordRoute", append([]interface{}{ctx}, opts...)...)
}

type mockRouteGuide_RecordRouteClient struct {
	mock.Mock
}

func NewMockRouteGuide_RecordRouteClient() *mockRouteGuide_RecordRouteClient {
	return &mockRouteGuide_RecordRouteClient{}
}

func (x *mockRouteGuide_RecordRouteClient) Header() (metadata.MD, error) {
	args := x.Called()
	return args.Get(0).(metadata.MD), args.Error(1)
}

func (x *mockRouteGuide_RecordRouteClient) Trailer() metadata.MD {
	args := x.Called()
	return args.Get(0).(metadata.MD)
}

func (x *mockRouteGuide_RecordRouteClient) CloseSend() error {
	args := x.Called()
	return args.Error(0)
}

func (x *mockRouteGuide_RecordRouteClient) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *mockRouteGuide_RecordRouteClient) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *mockRouteGuide_RecordRouteClient) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *mockRouteGuide_RecordRouteClient) Send(m *Point) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *mockRouteGuide_RecordRouteClient) OnSend(m interface{}) *mock.Call {
	return x.On("Send", m)
}

func (x *mockRouteGuide_RecordRouteClient) CloseAndRecv() (*RouteSummary, error) {
	args := x.Called()
	return args.Get(0).(*RouteSummary), args.Error(1)
}

func (x *mockRouteGuide_RecordRouteClient) OnCloseAndRecv() *mock.Call {
	return x.On("CloseAndRecv")
}

func (c *mockRouteGuideClient) RouteChat(ctx context.Context, opts ...grpc.CallOption) (RouteGuide_RouteChatClient, error) {
	opts0 := []interface{}{ctx}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(RouteGuide_RouteChatClient), args.Error(1)
}

func (c *mockRouteGuideClient) OnRouteChat(ctx interface{}, opts ...interface{}) *mock.Call {
	return c.On("RouteChat", append([]interface{}{ctx}, opts...)...)
}

type mockRouteGuide_RouteChatClient struct {
	mock.Mock
}

func NewMockRouteGuide_RouteChatClient() *mockRouteGuide_RouteChatClient {
	return &mockRouteGuide_RouteChatClient{}
}

func (x *mockRouteGuide_RouteChatClient) Header() (metadata.MD, error) {
	args := x.Called()
	return args.Get(0).(metadata.MD), args.Error(1)
}

func (x *mockRouteGuide_RouteChatClient) Trailer() metadata.MD {
	args := x.Called()
	return args.Get(0).(metadata.MD)
}

func (x *mockRouteGuide_RouteChatClient) CloseSend() error {
	args := x.Called()
	return args.Error(0)
}

func (x *mockRouteGuide_RouteChatClient) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *mockRouteGuide_RouteChatClient) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *mockRouteGuide_RouteChatClient) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *mockRouteGuide_RouteChatClient) Send(m *RouteNote) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *mockRouteGuide_RouteChatClient) OnSend(m interface{}) *mock.Call {
	return x.On("Send", m)
}

func (x *mockRouteGuide_RouteChatClient) Recv() (*RouteNote, error) {
	args := x.Called()
	return args.Get(0).(*RouteNote), args.Error(1)
}

func (x *mockRouteGuide_RouteChatClient) OnRecv() *mock.Call {
	return x.On("Recv")
}

type mockRouteGuideServer struct {
	mock.Mock
}

func NewMockRouteGuideServer() *mockRouteGuideServer {
	return &mockRouteGuideServer{}
}

func (s *mockRouteGuideServer) GetFeature(ctx context.Context, in *Point) (*Feature, error) {
	args := s.Called(ctx, in)
	return args.Get(0).(*Feature), args.Error(1)
}

func (s *mockRouteGuideServer) OnGetFeature(ctx interface{}, in interface{}) *mock.Call {
	return s.On("GetFeature", ctx, in)
}

func (s *mockRouteGuideServer) ListFeatures(in *Rectangle, out RouteGuide_ListFeaturesServer) error {
	args := s.Called(in, out)
	return args.Error(0)
}

func (s *mockRouteGuideServer) OnListFeatures(in interface{}, out interface{}) *mock.Call {
	return s.On("ListFeatures", in, out)
}

type mockRouteGuide_ListFeaturesServer struct {
	mock.Mock
}

func NewMockRouteGuide_ListFeaturesServer() *mockRouteGuide_ListFeaturesServer {
	return &mockRouteGuide_ListFeaturesServer{}
}

func (x *mockRouteGuide_ListFeaturesServer) SetHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *mockRouteGuide_ListFeaturesServer) SendHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *mockRouteGuide_ListFeaturesServer) SetTrailer(md metadata.MD) {
	_ = x.Called(md)
}

func (x *mockRouteGuide_ListFeaturesServer) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *mockRouteGuide_ListFeaturesServer) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *mockRouteGuide_ListFeaturesServer) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *mockRouteGuide_ListFeaturesServer) Send(m *Feature) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *mockRouteGuide_ListFeaturesServer) OnSend(m interface{}) *mock.Call {
	return x.On("Send", m)
}

func (s *mockRouteGuideServer) RecordRoute(out RouteGuide_RecordRouteServer) error {
	args := s.Called(out)
	return args.Error(0)
}

func (s *mockRouteGuideServer) OnRecordRoute(out interface{}) *mock.Call {
	return s.On("RecordRoute", out)
}

type mockRouteGuide_RecordRouteServer struct {
	mock.Mock
}

func NewMockRouteGuide_RecordRouteServer() *mockRouteGuide_RecordRouteServer {
	return &mockRouteGuide_RecordRouteServer{}
}

func (x *mockRouteGuide_RecordRouteServer) SetHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *mockRouteGuide_RecordRouteServer) SendHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *mockRouteGuide_RecordRouteServer) SetTrailer(md metadata.MD) {
	_ = x.Called(md)
}

func (x *mockRouteGuide_RecordRouteServer) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *mockRouteGuide_RecordRouteServer) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *mockRouteGuide_RecordRouteServer) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *mockRouteGuide_RecordRouteServer) Recv() (*Point, error) {
	args := x.Called()
	return args.Get(0).(*Point), args.Error(1)
}

func (x *mockRouteGuide_RecordRouteServer) OnRecv() *mock.Call {
	return x.On("Recv")
}

func (x *mockRouteGuide_RecordRouteServer) SendAndClose(m *RouteSummary) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *mockRouteGuide_RecordRouteServer) OnSendAndClose(m interface{}) *mock.Call {
	return x.On("SendAndClose", m)
}

func (s *mockRouteGuideServer) RouteChat(out RouteGuide_RouteChatServer) error {
	args := s.Called(out)
	return args.Error(0)
}

func (s *mockRouteGuideServer) OnRouteChat(out interface{}) *mock.Call {
	return s.On("RouteChat", out)
}

type mockRouteGuide_RouteChatServer struct {
	mock.Mock
}

func NewMockRouteGuide_RouteChatServer() *mockRouteGuide_RouteChatServer {
	return &mockRouteGuide_RouteChatServer{}
}

func (x *mockRouteGuide_RouteChatServer) SetHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *mockRouteGuide_RouteChatServer) SendHeader(md metadata.MD) error {
	args := x.Called(md)
	return args.Error(0)
}

func (x *mockRouteGuide_RouteChatServer) SetTrailer(md metadata.MD) {
	_ = x.Called(md)
}

func (x *mockRouteGuide_RouteChatServer) Context() context.Context {
	args := x.Called()
	return args.Get(0).(context.Context)
}

func (x *mockRouteGuide_RouteChatServer) SendMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *mockRouteGuide_RouteChatServer) RecvMsg(m interface{}) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *mockRouteGuide_RouteChatServer) Recv() (*RouteNote, error) {
	args := x.Called()
	return args.Get(0).(*RouteNote), args.Error(1)
}

func (x *mockRouteGuide_RouteChatServer) OnRecv() *mock.Call {
	return x.On("Recv")
}

func (x *mockRouteGuide_RouteChatServer) Send(m *RouteNote) error {
	args := x.Called(m)
	return args.Error(0)
}

func (x *mockRouteGuide_RouteChatServer) OnSend(m interface{}) *mock.Call {
	return x.On("Send", m)
}
