// Code generated by protoc-gen-go-grpcmock. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpcmock v0.5.0
// - protoc                 v3.21.1
// - testify                v1.7.1
// source: helloworld.proto

package helloworld

import (
	context "context"
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

func AnyHelloRequest() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*helloworld.HelloRequest")
}

func AnyHelloReply() mock.AnythingOfTypeArgument {
	return mock.AnythingOfType("*helloworld.HelloReply")
}

type mockGreeterClient struct {
	mock.Mock
}

func NewMockGreeterClient() *mockGreeterClient {
	return &mockGreeterClient{}
}

func (c *mockGreeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	opts0 := []interface{}{ctx, in}
	for _, opts1 := range opts {
		opts0 = append(opts0, opts1)
	}
	args := c.Called(opts0...)
	return args.Get(0).(*HelloReply), args.Error(1)
}

func (c *mockGreeterClient) OnSayHello(ctx interface{}, in interface{}, opts ...interface{}) *mock.Call {
	return c.On("SayHello", append([]interface{}{ctx, in}, opts...)...)
}

type mockGreeterServer struct {
	mock.Mock
}

func NewMockGreeterServer() *mockGreeterServer {
	return &mockGreeterServer{}
}

func (s *mockGreeterServer) SayHello(ctx context.Context, in *HelloRequest) (*HelloReply, error) {
	args := s.Called(ctx, in)
	return args.Get(0).(*HelloReply), args.Error(1)
}

func (s *mockGreeterServer) OnSayHello(ctx interface{}, in interface{}) *mock.Call {
	return s.On("SayHello", ctx, in)
}
