name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:

  build:
    name: Build, Lint & Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Build
      run: go build -o build/protoc-gen-go-grpcmock ./cmd/protoc-gen-go-grpcmock

    - name: Test
      run: go test -v -race -cover ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
