name: Goreleaser

on:
  push:
    tags:
      - '*'

jobs:

  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}